# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editar_Registro_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class EditarRegistro(object):
    def setupUi(self, EditarRegistro):
        EditarRegistro.setObjectName("EditarRegistro")
        EditarRegistro.resize(460, 603)
        self.centralwidget = QtWidgets.QWidget(EditarRegistro)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_titulo_editar = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo_editar.setGeometry(QtCore.QRect(130, 30, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo_editar.setFont(font)
        self.lbl_titulo_editar.setObjectName("lbl_titulo_editar")
        self.lbl_tipo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tipo.setGeometry(QtCore.QRect(30, 100, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tipo.setFont(font)
        self.lbl_tipo.setObjectName("lbl_tipo")
        self.lbl_marca = QtWidgets.QLabel(self.centralwidget)
        self.lbl_marca.setGeometry(QtCore.QRect(30, 175, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_marca.setFont(font)
        self.lbl_marca.setObjectName("lbl_marca")
        self.lbl_modelo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_modelo.setGeometry(QtCore.QRect(30, 250, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_modelo.setFont(font)
        self.lbl_modelo.setObjectName("lbl_modelo")
        self.lbl_gama = QtWidgets.QLabel(self.centralwidget)
        self.lbl_gama.setGeometry(QtCore.QRect(30, 325, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gama.setFont(font)
        self.lbl_gama.setObjectName("lbl_gama")
        self.lbl_precio = QtWidgets.QLabel(self.centralwidget)
        self.lbl_precio.setGeometry(QtCore.QRect(30, 400, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_precio.setFont(font)
        self.lbl_precio.setObjectName("lbl_precio")
        self.cbx_tipo = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_tipo.setGeometry(QtCore.QRect(130, 110, 220, 30))
        self.cbx_tipo.setObjectName("cbx_tipo")
        self.cbx_tipo.addItem("")
        self.cbx_tipo.addItem("")
        self.cbx_tipo.addItem("")
        self.cbx_tipo.addItem("")
        self.cbx_tipo.addItem("")
        self.cbx_tipo.addItem("")
        self.cbx_tipo.addItem("")
        self.txt_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_marca.setGeometry(QtCore.QRect(130, 180, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txt_marca.setFont(font)
        self.txt_marca.setObjectName("txt_marca")
        self.txt_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_modelo.setGeometry(QtCore.QRect(130, 250, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txt_modelo.setFont(font)
        self.txt_modelo.setObjectName("txt_modelo")
        self.cbx_gama = QtWidgets.QComboBox(self.centralwidget)
        self.cbx_gama.setGeometry(QtCore.QRect(130, 320, 220, 30))
        self.cbx_gama.setObjectName("cbx_gama")
        self.cbx_gama.addItem("")
        self.cbx_gama.addItem("")
        self.cbx_gama.addItem("")
        self.txt_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_precio.setGeometry(QtCore.QRect(130, 390, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txt_precio.setFont(font)
        self.txt_precio.setObjectName("txt_precio")
        self.btn_editar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_editar.setGeometry(QtCore.QRect(150, 490, 150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_editar.setFont(font)
        self.btn_editar.setObjectName("btn_editar")
        EditarRegistro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EditarRegistro)
        self.statusbar.setObjectName("statusbar")
        EditarRegistro.setStatusBar(self.statusbar)

        self.retranslateUi(EditarRegistro)
        QtCore.QMetaObject.connectSlotsByName(EditarRegistro)

    def retranslateUi(self, EditarRegistro):
        _translate = QtCore.QCoreApplication.translate
        EditarRegistro.setWindowTitle(_translate("EditarRegistro", "Editar producto"))
        self.lbl_titulo_editar.setText(_translate("EditarRegistro", "Editar producto"))
        self.lbl_tipo.setText(_translate("EditarRegistro", "Tipo"))
        self.lbl_marca.setText(_translate("EditarRegistro", "Marca"))
        self.lbl_modelo.setText(_translate("EditarRegistro", "Modelo"))
        self.lbl_gama.setText(_translate("EditarRegistro", "Gama"))
        self.lbl_precio.setText(_translate("EditarRegistro", "Precio"))
        self.cbx_tipo.setItemText(0, _translate("EditarRegistro", "Accessory"))
        self.cbx_tipo.setItemText(1, _translate("EditarRegistro", "Display"))
        self.cbx_tipo.setItemText(2, _translate("EditarRegistro", "Gaming Chair"))
        self.cbx_tipo.setItemText(3, _translate("EditarRegistro", "Headset"))
        self.cbx_tipo.setItemText(4, _translate("EditarRegistro", "Keyboard"))
        self.cbx_tipo.setItemText(5, _translate("EditarRegistro", "Mouse"))
        self.cbx_tipo.setItemText(6, _translate("EditarRegistro", "Wireless Audio"))
        self.cbx_gama.setItemText(0, _translate("EditarRegistro", "Basic"))
        self.cbx_gama.setItemText(1, _translate("EditarRegistro", "Advance"))
        self.cbx_gama.setItemText(2, _translate("EditarRegistro", "Elite"))
        self.btn_editar.setText(_translate("EditarRegistro", "Guardar Cambios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditarRegistro = QtWidgets.QMainWindow()
    ui = EditarRegistro()
    ui.setupUi(EditarRegistro)
    EditarRegistro.show()
    sys.exit(app.exec_())
