# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class CalculadoraDialog(object):
    def setupUi(self, CalculadoraDialog):
        CalculadoraDialog.setObjectName("CalculadoraDialog")
        CalculadoraDialog.resize(463, 266)
        self.txt_primer_numero = QtWidgets.QLineEdit(CalculadoraDialog)
        self.txt_primer_numero.setGeometry(QtCore.QRect(210, 50, 181, 20))
        self.txt_primer_numero.setObjectName("txt_primer_numero")
        self.lbl_calculadora = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_calculadora.setGeometry(QtCore.QRect(200, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_calculadora.setFont(font)
        self.lbl_calculadora.setObjectName("lbl_calculadora")
        self.lbl_introduzca_primer_numero = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_introduzca_primer_numero.setGeometry(QtCore.QRect(30, 50, 141, 16))
        self.lbl_introduzca_primer_numero.setObjectName("lbl_introduzca_primer_numero")
        self.lbl_introduzca_segundo_numero = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_introduzca_segundo_numero.setGeometry(QtCore.QRect(30, 80, 161, 16))
        self.lbl_introduzca_segundo_numero.setObjectName("lbl_introduzca_segundo_numero")
        self.txt_segundo_numero = QtWidgets.QLineEdit(CalculadoraDialog)
        self.txt_segundo_numero.setGeometry(QtCore.QRect(210, 80, 181, 20))
        self.txt_segundo_numero.setObjectName("txt_segundo_numero")
        self.txt_resultado = QtWidgets.QLineEdit(CalculadoraDialog)
        self.txt_resultado.setGeometry(QtCore.QRect(210, 120, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_resultado.setFont(font)
        self.txt_resultado.setObjectName("txt_resultado")
        self.lbl_resultado = QtWidgets.QLabel(CalculadoraDialog)
        self.lbl_resultado.setGeometry(QtCore.QRect(100, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_resultado.setFont(font)
        self.lbl_resultado.setObjectName("lbl_resultado")
        self.btn_sumar = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_sumar.setGeometry(QtCore.QRect(60, 160, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sumar.setFont(font)
        self.btn_sumar.setObjectName("btn_sumar")
        self.btn_restar = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_restar.setGeometry(QtCore.QRect(160, 160, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_restar.setFont(font)
        self.btn_restar.setObjectName("btn_restar")
        self.btn_multiplicar = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_multiplicar.setGeometry(QtCore.QRect(260, 160, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multiplicar.setFont(font)
        self.btn_multiplicar.setObjectName("btn_multiplicar")
        self.btn_dividir = QtWidgets.QPushButton(CalculadoraDialog)
        self.btn_dividir.setGeometry(QtCore.QRect(360, 160, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dividir.setFont(font)
        self.btn_dividir.setObjectName("btn_dividir")
        self.pushButton_5 = QtWidgets.QPushButton(CalculadoraDialog)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 220, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(CalculadoraDialog)
        self.pushButton_5.clicked.connect(self.txt_primer_numero.clear)
        self.pushButton_5.clicked.connect(self.txt_segundo_numero.clear)
        self.pushButton_5.clicked.connect(self.txt_resultado.clear)
        QtCore.QMetaObject.connectSlotsByName(CalculadoraDialog)

    def retranslateUi(self, CalculadoraDialog):
        _translate = QtCore.QCoreApplication.translate
        CalculadoraDialog.setWindowTitle(_translate("CalculadoraDialog", "Caculadora"))
        self.lbl_calculadora.setText(_translate("CalculadoraDialog", "Calculadora"))
        self.lbl_introduzca_primer_numero.setText(_translate("CalculadoraDialog", "Introduzca el primer número"))
        self.lbl_introduzca_segundo_numero.setText(_translate("CalculadoraDialog", "Introduzca el segundo número"))
        self.lbl_resultado.setText(_translate("CalculadoraDialog", "RESULTADO"))
        self.btn_sumar.setText(_translate("CalculadoraDialog", "+"))
        self.btn_restar.setText(_translate("CalculadoraDialog", "-"))
        self.btn_multiplicar.setText(_translate("CalculadoraDialog", "*"))
        self.btn_dividir.setText(_translate("CalculadoraDialog", "/"))
        self.pushButton_5.setText(_translate("CalculadoraDialog", "BORRAR"))
