# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConversorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

'''
****** EJECUTAR DESDE ConversorMonedasApplication.py ******

'''

from PyQt5 import QtCore, QtGui, QtWidgets


class ConversorDialog(object):
    def setupUi(self, ConversorDialog):
        ConversorDialog.setObjectName("ConversorDialog")
        ConversorDialog.resize(477, 647)
        ConversorDialog.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.lbl_titulo = QtWidgets.QLabel(ConversorDialog)
        self.lbl_titulo.setGeometry(QtCore.QRect(50, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_euro = QtWidgets.QLabel(ConversorDialog)
        self.lbl_euro.setGeometry(QtCore.QRect(60, 60, 51, 51))
        self.lbl_euro.setText("")
        self.lbl_euro.setPixmap(QtGui.QPixmap("images/UE2.png"))
        self.lbl_euro.setScaledContents(True)
        self.lbl_euro.setObjectName("lbl_euro")
        self.txt_cantidad = QtWidgets.QLineEdit(ConversorDialog)
        self.txt_cantidad.setGeometry(QtCore.QRect(140, 90, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_cantidad.setFont(font)
        self.txt_cantidad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_cantidad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_cantidad.setObjectName("txt_cantidad")
        self.verticalLayoutWidget = QtWidgets.QWidget(ConversorDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 150, 121, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vly_rbns = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vly_rbns.setContentsMargins(0, 0, 0, 0)
        self.vly_rbns.setObjectName("vly_rbns")
        self.rbn_usa = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbn_usa.setFont(font)
        self.rbn_usa.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/USA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbn_usa.setIcon(icon)
        self.rbn_usa.setIconSize(QtCore.QSize(48, 48))
        self.rbn_usa.setObjectName("rbn_usa")
        self.vly_rbns.addWidget(self.rbn_usa)
        self.rbn_uk = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbn_uk.setFont(font)
        self.rbn_uk.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/UK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbn_uk.setIcon(icon1)
        self.rbn_uk.setIconSize(QtCore.QSize(48, 48))
        self.rbn_uk.setObjectName("rbn_uk")
        self.vly_rbns.addWidget(self.rbn_uk)
        self.rbn_jpn = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbn_jpn.setFont(font)
        self.rbn_jpn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/JP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbn_jpn.setIcon(icon2)
        self.rbn_jpn.setIconSize(QtCore.QSize(48, 48))
        self.rbn_jpn.setObjectName("rbn_jpn")
        self.vly_rbns.addWidget(self.rbn_jpn)
        self.rbn_china = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbn_china.setFont(font)
        self.rbn_china.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/CHN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbn_china.setIcon(icon3)
        self.rbn_china.setIconSize(QtCore.QSize(48, 48))
        self.rbn_china.setObjectName("rbn_china")
        self.vly_rbns.addWidget(self.rbn_china)
        self.rbn_rusia = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbn_rusia.setFont(font)
        self.rbn_rusia.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/RU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbn_rusia.setIcon(icon4)
        self.rbn_rusia.setIconSize(QtCore.QSize(48, 48))
        self.rbn_rusia.setObjectName("rbn_rusia")
        self.vly_rbns.addWidget(self.rbn_rusia)
        self.rbn_brasil = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbn_brasil.setFont(font)
        self.rbn_brasil.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/BR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbn_brasil.setIcon(icon5)
        self.rbn_brasil.setIconSize(QtCore.QSize(48, 48))
        self.rbn_brasil.setObjectName("rbn_brasil")
        self.vly_rbns.addWidget(self.rbn_brasil)
        self.lbl_dolar = QtWidgets.QLabel(ConversorDialog)
        self.lbl_dolar.setGeometry(QtCore.QRect(210, 170, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dolar.setFont(font)
        self.lbl_dolar.setText("")
        self.lbl_dolar.setObjectName("lbl_dolar")
        self.lbl_libra = QtWidgets.QLabel(ConversorDialog)
        self.lbl_libra.setGeometry(QtCore.QRect(210, 240, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_libra.setFont(font)
        self.lbl_libra.setText("")
        self.lbl_libra.setObjectName("lbl_libra")
        self.lbl_yen = QtWidgets.QLabel(ConversorDialog)
        self.lbl_yen.setGeometry(QtCore.QRect(210, 300, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_yen.setFont(font)
        self.lbl_yen.setText("")
        self.lbl_yen.setObjectName("lbl_yen")
        self.lbl_yuan = QtWidgets.QLabel(ConversorDialog)
        self.lbl_yuan.setGeometry(QtCore.QRect(210, 360, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_yuan.setFont(font)
        self.lbl_yuan.setText("")
        self.lbl_yuan.setObjectName("lbl_yuan")
        self.lbl_rublo = QtWidgets.QLabel(ConversorDialog)
        self.lbl_rublo.setGeometry(QtCore.QRect(210, 420, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rublo.setFont(font)
        self.lbl_rublo.setText("")
        self.lbl_rublo.setObjectName("lbl_rublo")
        self.lbl_real = QtWidgets.QLabel(ConversorDialog)
        self.lbl_real.setGeometry(QtCore.QRect(210, 490, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_real.setFont(font)
        self.lbl_real.setText("")
        self.lbl_real.setObjectName("lbl_real")
        self.btn_reset = QtWidgets.QPushButton(ConversorDialog)
        self.btn_reset.setEnabled(True)
        self.btn_reset.setGeometry(QtCore.QRect(190, 540, 90, 90))
        self.btn_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reset.setStyleSheet("border-color: rgb(213, 213, 213);\n"
"background-color: rgb(213, 213, 213);")
        self.btn_reset.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reset.setIcon(icon6)
        self.btn_reset.setIconSize(QtCore.QSize(128, 128))
        self.btn_reset.setAutoDefault(False)
        self.btn_reset.setFlat(True)
        self.btn_reset.setObjectName("btn_reset")
        self.lbl_introduce_euros = QtWidgets.QLabel(ConversorDialog)
        self.lbl_introduce_euros.setGeometry(QtCore.QRect(140, 60, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_introduce_euros.setFont(font)
        self.lbl_introduce_euros.setObjectName("lbl_introduce_euros")
        self.lbl_selecciona_divisa = QtWidgets.QLabel(ConversorDialog)
        self.lbl_selecciona_divisa.setGeometry(QtCore.QRect(80, 120, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_selecciona_divisa.setFont(font)
        self.lbl_selecciona_divisa.setObjectName("lbl_selecciona_divisa")

        self.retranslateUi(ConversorDialog)
        self.btn_reset.clicked.connect(self.txt_cantidad.clear)
        self.btn_reset.clicked.connect(self.lbl_dolar.clear)
        self.btn_reset.clicked.connect(self.lbl_libra.clear)
        self.btn_reset.clicked.connect(self.lbl_yen.clear)
        self.btn_reset.clicked.connect(self.lbl_yuan.clear)
        self.btn_reset.clicked.connect(self.lbl_rublo.clear)
        self.btn_reset.clicked.connect(self.lbl_real.clear)
        QtCore.QMetaObject.connectSlotsByName(ConversorDialog)

    def retranslateUi(self, ConversorDialog):
        _translate = QtCore.QCoreApplication.translate
        ConversorDialog.setWindowTitle(_translate("ConversorDialog", "Conversor divisas"))
        self.lbl_titulo.setText(_translate("ConversorDialog", "CONVERSOR DE DIVISAS"))
        self.lbl_introduce_euros.setText(_translate("ConversorDialog", "Introduce el importe en euros"))
        self.lbl_selecciona_divisa.setText(_translate("ConversorDialog", "Selecciona la divisa a convertir"))
